[project]
name = "src"
version = "0.0.1"
description = "MLOps production project"
authors = [{name= "Arpit Dhiman", email= "arpitdhiman184@gmail.com"}]

[tool.setuptools]
packages = {find = {}}

[tool.setuptools.dynamic]
dependencies = {file = "requirements.txt"}